language: python
python:
  - "3.8"
sudo: required

services:
  - docker

before_install:
  - echo 'test'
  # install heroku CLI
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
    # login to docker registries (dockerhub + heroku)
  #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
  - heroku login
  - heroku container:login

  script:
  # - docker build -t cisaia/apisimplon:latest . 
  #- docker tag /apisimplon registry.heroku.com/$HEROKU_APP_NAME/web

deploy:
  provider: script
  api_key: 
    secure: "$HEROKU_AUTH_TOKEN"
  script: 

    # docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:push web --app $HEROKU_APP_NAME
    heroku container:release web --app $HEROKU_APP_NAME
  on:
    branch: master